=== Marcombo/El-gran-libro-de-Kotlin/src/main/resources/xml/B3h_TRF_v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:annotation>
        <xs:documentation xml:lang="es">Esquema que define Lista de perfiles y tarifas de título (fichero de tarifas) (TRF) (TLV=B3h)</xs:documentation>
    </xs:annotation>
    <xs:element name="Empresa_Propietaria_Cod" type="xs:string"/>
    <xs:element name="Empresa_Propietaria_Perf" type="xs:string"/>
    <xs:element name="Fecha_Cambio_Tarifa" type="xs:string"/>
    <xs:element name="Fecha_Fin_Admision" type="xs:string"/>
    <xs:element name="Fecha_Inicio_Admision" type="xs:string"/>
    <xs:element name="Informacion_Tarifas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Titulo" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="TipoTLV" use="required">
                <xs:simpleType>
                    <xs:annotation>
                        <xs:documentation xml:lang="es">Esta TLV debe tener siempre uno de los valores especificados en la restricción</xs:documentation>
                    </xs:annotation>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="B3|B3h"/>
                    </xs:restriction>    
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="Version" use="required">
                <xs:simpleType>
                    <xs:annotation>
                        <xs:documentation xml:lang="es">El número de version debe ser siempre 1.0</xs:documentation>
                    </xs:annotation>
                    <xs:restriction base="xs:float">
                        <xs:pattern value="1.0"/>
                    </xs:restriction>    
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="Perfil">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Empresa_Propietaria_Perf"/>
                <xs:element ref="Tarifa" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="Codigo" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Tarifa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Tipo_Unidades" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="TipoUnidades" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Unidades" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Fecha_Inicio_Admision" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Fecha_Cambio_Tarifa" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Fecha_Fin_Admision" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="TipoUnidades" type="xs:string"/>
    <xs:element name="Tipo_Unidades" type="xs:string"/>
    <xs:element name="Titulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Empresa_Propietaria_Cod" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Perfil" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="Codigo" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Unidades" type="xs:int"/>
</xs:schema>

=== Marcombo/El-gran-libro-de-Kotlin/src/main/resources/xml/B3h_TRF_v1.0.xml
<?xml version="1.0" encoding="ISO-8859-15"?>
<?xml-stylesheet type="text/xsl" href=".\B3h_TRF_v1.0.xsl"?>
<Informacion_Tarifas TipoTLV="B3h" Version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\B3h_TRF_v1.0.xsd">
 <Titulo Codigo="100Bh">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Perfil Codigo="01h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>      
         <Unidades>54600</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>54600</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
  <Perfil Codigo="03h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>35000</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>35000</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
 </Titulo>
 <Titulo Codigo="100Ch">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Perfil Codigo="01h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>63700</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>63700</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
  <Perfil Codigo="03h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>39600</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>39600</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
 </Titulo>
 <Titulo Codigo="100Dh">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Perfil Codigo="01h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>72000</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>72000</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
  <Perfil Codigo="03h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>45000</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>45000</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
 </Titulo>
 <Titulo Codigo="100Eh">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Perfil Codigo="01h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>82000</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>82000</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
  <Perfil Codigo="03h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>51600</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>51600</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
 </Titulo>
 <Titulo Codigo="100Fh">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Perfil Codigo="01h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>89500</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>89500</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
  <Perfil Codigo="03h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>56200</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>56200</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
 </Titulo>
 <Titulo Codigo="1001h">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Perfil Codigo="01h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>5460</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>5460</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
 </Titulo>
 <Titulo Codigo="1002h">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Perfil Codigo="01h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>6370</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>6370</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>19/03/2024</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>20/03/2025</Fecha_Fin_Admision>
      </Tarifa>
  </Perfil>
 </Titulo>
 <Titulo Codigo="1003h">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Perfil Codigo="01h">
      <Empresa_Propietaria_Perf>01h</Empresa_Propietaria_Perf>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>7200</Unidades>
         <Fecha_Inicio_Admision>01/01/2019</Fecha_Inicio_Admision>
         <Fecha_Cambio_Tarifa>01/01/2020</Fecha_Cambio_Tarifa>
         <Fecha_Fin_Admision>11/02/2020</Fecha_Fin_Admision>
      </Tarifa>
      <Tarifa>
         <Tipo_Unidades>02h</Tipo_Unidades>
         <Unidades>7200</Unidades>
         <Fecha_Inicio_Admision>01/11/2019</Fecha_Inicio_Admision>
